### ISSUE TITLE
Babel 3.0.0-pl — Babel Links display the wrong language 

### ISSUE THREAD

**Issue by berj** [mikrobi/babel#149]
Modx 2.5.2
Web context | cultureKey = fr
English contact | cultureKey = en

I update from Babel 3.0.0-rc1 to 3.0.0-pl. Everything works fine except for Babel Links

In version 3.0.0-rc1
Babel link in Web context indicates => English
Babel link in English context indicates => Français

In version 3.0.0-pl
Babel link in Web context indicates => English
Babel link in English context indicates => French

I flush the cache on the server but the problem remains.

Thank you for your help

**Comment by goldsky** [comment]
This happens because babel is now using IANA's language string, not by
lexicon.
To revert back to previous way, create a chunk for babelLinks' template and
use previous template, because current version uses the new chunk
https://github.com/mikrobi/babel/blob/master/core/components/babel/elements/chunks/babellink.chunk.tpl
(Check the commit)
