### ISSUE TITLE
Error: Could not load context from babel class and snippet

### ISSUE THREAD

**Issue by sebastian-marinescu** [mikrobi/babel#178]
I get irregular logs telling me 

> Could not load context: "web-de"

or 

> Could not load context: "web-it"

The contexts exist, so what's going on there?

**Comment by sebastian-marinescu** [comment]
The dash-character is a valid character for a context-name, so this isn't a viable solution. 
Also almost all the time it doesn't log something like this. This is happening *irregularly*. Why?

**Comment by gravino81** [comment]
Same problem, but the problem it is only if the cache page is generated by admin, if is the anonymous at generating the cache the error no occurs and languages appears in [[BabelLinks]] output, otherwise it does not appear.

I have many other sites configured like this, but they don't have this problem.

Does anyone have any idea?

All ACL is correctly setting for all context!
Babel 3.0.0-pl
Modx 2.7.2-pl
PHP Version 7.2.27

**Comment by gravino81** [comment]
> Same problem, but the problem it is only if the cache page is generated by admin, if is the anonymous at generating the cache the error no occurs and languages appears in [[BabelLinks]] output, otherwise it does not appear.
> 
> I have many other sites configured like this, but they don't have this problem.
> 
> Does anyone have any idea?
> 
> Context names: web,en,fr
> All ACL is correctly setting for all context!
> Babel 3.0.0-pl
> Modx 2.7.2-pl
> PHP Version testing 7.1.33 or 7.2.27

I solved re-installing modx!

**Comment by travisbotello** [comment]
> Same problem, but the problem it is only if the cache page is generated by admin, if is the anonymous at generating the cache the error no occurs and languages appears in [[BabelLinks]] output, otherwise it does not appear.

I can reproduce exactly the same issue. Any ideas?

**Comment by travisbotello** [comment]
Solution is pretty easy and this is definitely not a bug. After you created a new context and added permissions for admin user you have to reload permission or logout/login so that the admin permissions are taking effect on the new context. No need to re-install modx. I think this can be closed now.
