### ISSUE TITLE
Not able to link by ID after duplicating context

### ISSUE THREAD

**Issue by Jorgenh** [mikrobi/babel#89]
When i duplicate a context to add another language (including all resources) i'm not able to link those pages to resources in the other contexts.
I receive the following error: "Modx Resource # is already linked with other resources"

See also: http://forums.modx.com/thread/91233/babel-modx-resource-is-already-linked-with-other-resources

**Comment by Mikmaister** [comment]
Is there any workaround for this? 
example: Clearing already set languages from their id's? (I got 300pages/language, so manually resetting these wouldnt be very nice) in the link of Jorgenh is solved by 
>1. Go to Babel plugin
>2. CTRL+F = 'target resource is already linked with other'
>3. Comment two lines: "$errorParameter = ..." and "throw new Exception ..."
Is this good answer to this problem?

**Comment by nicar** [comment]
Quite old this thread, but I just ran into the same problem.
I solved it simply by removing the babel-relevant settings from the database. In my case babel had linked a resource to itself and therefore was blocked.

* Access your database
* Find the table `modx_site_tmplvar_contentvalues`
* The babel linking looks like this: `web:34;en:96` (context:res_id) – in this case exactly the same setting will be found for `contentid` 34 (web resource) & 96 (en resource)
* The settings have to be the same for each of the linked pages, otherwise you will run into an Error like "A Translation already exists at .."
* If you have only a few pages you can change the settings by hand, otherwise you could execute some SQL with find / replace to delete the duplicate context entry in the string.

**Comment by goldsky** [comment]
Bad news, MODX doesn't provide an Event to hack in context duplication.
